#!/usr/bin/env zsh

AM_GIT_SYM=G
AM_HG_SYM=H
AM_SVN_SYM=S
PLIB_GIT_PUSH_SYM=↑
PLIB_GIT_PULL_SYM=↓
PLIB_GIT_TRACKED_COLOR=078
PLIB_GIT_UNTRACKED_COLOR=208

[ -z "${PROMPT_START_TAG}" ] && PROMPT_START_TAG=''
[ -z "${PROMPT_END_TAG}" ] && PROMPT_END_TAG=''
[ -z "${PROMPT_START_TAG_COLOR}" ] && PROMPT_START_TAG_COLOR=39
[ -z "${PROMPT_END_TAG_COLOR}" ] && PROMPT_END_TAG_COLOR=39
