#!/usr/bin/env zsh

## ===> THEME
#  AM_THEME=default

## ===> CONFIGS
#  AM_ASYNC_L_PROMPT=1
#  AM_INITIAL_LINE_FEED=0
#  AM_USE_NERD_FONT=1
#  AM_DIR_EXPANSION_LEVEL=1

## ===> VI PROMPT
#  AM_ENABLE_VI_PROMPT=1
#  AM_VIM_INSERT_SYM='(i)'
#  AM_VIM_NORMAL_SYM='(n)'
#  AM_VI_PROMPT_POS='left_end'

## ===> SYMBOLS
#  AM_VERSION_PROMPT_SEP='|'
#  AM_JAVA_SYM='JAVA:'
#  AM_PY_SYM='PY:'
#  AM_RB_SYM='RB:'
#  AM_GO_SYM='GO:'
#  AM_ELIXIR_SYM='EX:'
#  AM_CRYSTAL_SYM='CR:'
#  AM_NODE_SYM='⬡ '
#  AM_PHP_SYM='PHP:'
#  AM_HG_SYM='H'
#  AM_SVN_SYM='S'
#  AM_SSH_SYM='[S]'
#  AM_GIT_SYM='G'
#  AM_GIT_REBASING_SYMBOL='⇋'
#  AM_GIT_PUSH_SYM='↑'
#  AM_GIT_PULL_SYM='↓'
#  AM_GIT_STASH_SYM='@'
#  AM_GIT_BARE_SYM='☢'
#  AM_PROMPT_START_TAG=''
#  AM_PROMPT_END_TAG=''

## ===> COLORS
#  AM_VCS_COLOR=248
#  AM_SSH_COLOR=143
#  AM_NORMAL_COLOR=39
#  AM_ERROR_COLOR=208
#  AM_REV_COLOR=248
#  AM_BRANCH_COLOR=78
#  AM_LEFT_RIGHT_COLOR=222
#  AM_STASH_COLOR=222
#  AM_BARE_COLOR=222
#  AM_COMMIT_SINCE_COLOR=244
#  AM_FADE_COLOR=242
#  AM_VENV_COLOR=245
#  AM_PYTHON_COLOR=40
#  AM_RUBY_COLOR=196
#  AM_JAVA_COLOR=178
#  AM_GO_COLOR=81
#  AM_ELIXIR_COLOR=81
#  AM_CRYSTAL_COLOR=8
#  AM_NODE_COLOR=2
#  AM_PHP_COLOR=5
#  AM_TIMER_COLOR=248
#  AM_VIINS_COLOR=39
#  AM_VICMD_COLOR=208
#  AM_PROMPT_START_TAG_COLOR=39
#  AM_PROMPT_END_TAG_COLOR=39
#  AM_GIT_TRACKED_COLOR=78
#  AM_GIT_UN_TRACKED_COLOR=208
